### ISSUE TITLE
[Checklist #3] Options analysis component

### ISSUE THREAD

**Issue by chrismclarke** [e-picsa/picsa-apps#106]
## Next Priorities
- [x] Ability to export as image to share #238
- [x] Separate options lists for livestock and livelihood options #255 
---

## Feedback TODO
**Updates 2023-09**
- [ ] Fix bug where adding new option does not always appear in expected order #255

**2023-03 UoR feedback**
- [ ] Will need a careful design for direct to farmer App
- [ ] Extension_farmer app add information about pests and diseases and market information as additional columns to matrix

---
## Feedback Completed
- [x] Ability to record multiple sets of options, e.g. initial screen and separate pages for crop, livestock or livelihood option lists
- [x] Ability to go direct to stepper section when clicking on row, e.g. clicking on the _Time_ entry opens stepper on step 7
- [x] Allow users to edit their input by tapping on the same row
- [x] Add support for icons
- [x] Incorporate a mat-stepper to make it easier for users to go back and forth between pages #108 
- [x] Add risks section to stepper (seems to be missing)
- [x] Auto-save on every edit (instead of manual save at end or using save changes button, even if data incomplete)
- [x] Add support for translations (https://docs.picsa.app/translations) #127 
- [x] Save to database #128
- [x] Add page to view and edit all saved lists of options
- [x] Integrate into main app #120

---

**Additional context**
Icons will require import of the `MatIconModule`. which should allow inclusion of any standard material icons. You should be able to test this with an example, e.g. `<mat-icon>home</mat-icon>`

In order to use custom icons you will need to add svg files into the assets folder, and register them in the same way as `apps\picsa-tools\budget-tool\src\app\app.component.ts`. Icons can then be imported with syntax `<mat-icon svgIcon="picsa_icon_name"></mat-icon>
More info in docs https://material.angular.io/components/icon/overview

**Comment by chrismclarke** [comment]
Tracking for specific app features and improvements has been moved to [E-PICSA Issue Triage](https://docs.google.com/spreadsheets/d/17OqUtZZO5aznegT1TSGPtdYOhmtfhBYycgIYx7z0LTs/edit?usp=sharing) Google Sheet instead. Closing here
