### ISSUE TITLE
[Feedback] - ICT Consultants

### ISSUE THREAD

**Issue by chrismclarke** [e-picsa/picsa-apps#115]
**Partners**
Zambia - Agricomm - Deliso (project lead),
Malawi - JIMAT - Francis (project lead), Grace

List of feedback items from in-country testing teams

Likely many of these will be duplicated in other checklist/tools, but keeping a combined list here just to make it easier to provide updates to the teams on development

## 2023-12 (PICSA Planning Mettings)
**Farmer Activities**
Moved to #6

**App General**
- [x] Implement start screen to help identify farmer/extension version and update home screen accordingly
- [x] Farmer stories integrated as standalone videos in own section (initially resources)... possibly no immediate dev

**User Management**
- [ ] User profile popup to make it easier to manage data that feeds into multiple tools, e.g. district/location/station, extension/farmer, extension name (monitoring), training cohort (could be used to access specific forms, with password access)
- [ ] Possible use of cohorts to group permissions/access across users (with enrollment system)
- [ ] Store key user info to pass into tools (e.g. climate station)
- [ ] User backup (linked to auth system)

**Monitoring**
- [x] Monitoring tool access/security
- [x] Review use of kobo toolbox (if required + server gdpr)

**Analytics**
- [x] #220
- [ ] Analytics opt-in and out

**Misc**
- [ ] Communication component to be deprioritised (focus on video content to support building support networks as opposed to in-app notifications etc.)
- [ ] Add links to CCARDESA Resources
- [ ] Improve way app shared (e.g. links to apk, sideloading instructions, video)
- [ ] Orientation sizing - suggested being more specific for certain tools/device sizes

## 2023-12 (Direct to farmer and planning workshop)
[Farmer Report Summary](https://docs.google.com/document/d/1bDGrydn8adXxrw3yKSKSgdfMYG4YjslC/edit)
- [ ] Make APK easier to share
- [ ] Increase video function button sizes (if possible), particularly playback slider
- [ ] Fix whatsapp group links
- [ ] Add tab for climate tool and crop info in same section for probability and risk activity
- [ ] Consider enforcing landscape/portrait orientation for certain tools (tbd what would be best, tricky as sometimes scrolling portrait is still better than landscape, e.g. budget tool on small phone)
- [ ] User data backup

### Malawi
[Malawi Report](https://docs.google.com/document/d/1ISTu0JfQ7VJoTbheqci0kgNmZcNrwWnH/edit?usp=sharing&ouid=104305379976701296755&rtpof=true&sd=true)

**Budget Tool**
- [x] Ability to edit months #146

### Zambia
[Zambia Report](https://docs.google.com/document/d/1knxXTXZk0fURDkfIkPv-o_hptpm4Tihq/edit?usp=sharing&ouid=104305379976701296755&rtpof=true&sd=true)

**Translations**

- [ ] Bemba language added if possible
- [x] Change nyanja-> chewa, update translations #144
- [x] Select language available within every tool (e.g. sidebar) #146 (budget and climate)
- [ ] Crop probability tool translations

**Budget Tool**
- [ ] Potential missing inputs for budget tool (needs clarification)

**Crop Probability**
- [x] Add cotton, cassava, sweet potatoes, rice, bamabara nuts, tobacco
- [x] Start date in Jan

**Monitoring**
- [ ] Form should include challenges faced
- [ ] Form could include age segments
- [ ] Organise who will receive, e.g. district level e.g. SAO, EMO, CHO. 

**Resources**
- [ ] Live weather in app (more prominent)

## 2023-03-16
**Translations**
- [x] Use separate lists for Malawi and Zambia
- [x] Capture missing translations
- [ ] Add back button after changing language

**General**
- [ ] Tutorial videos for all (e.g. https://introjs.com/)
- [ ] Voice instructions if possible

**Budget tool** - tracked in #51

**Comment by chrismclarke** [comment]
@gkebirungi - would you be happy keeping an eye on development updates and give feedback to the group when we make updates that address points raised?

I'll also add to our next meeting agenda to discuss if we want to prioritise any of them in particular

**Comment by chrismclarke** [comment]
Tracking for specific app features and improvements has been moved to [E-PICSA Issue Triage](https://docs.google.com/spreadsheets/d/17OqUtZZO5aznegT1TSGPtdYOhmtfhBYycgIYx7z0LTs/edit?usp=sharing) Google Sheet instead. Closing here
