### ISSUE TITLE
[Checklist #4] Participatory Budgets

### ISSUE THREAD

**Issue by chrismclarke** [e-picsa/picsa-apps#51]
## 2024-02 Next Priorities
- [ ] Interactive Tour
- [x] #230
- [ ] Core improvements (data binding and shared libs)
- [ ] What-if scenario mode (takes a copy of the budget to allow testing changes on top)
---

## Feedback TODO
**UoR Feedback Issues**
- [ ] Long term planning
- [x] Repeat columns
- [ ] Add actuals against budget
- [x] Capture asset in the summary
- [ ] Add more templates (short-term& long-term investment type: woodlots, dairy cows…etc)
- [ ] #102

**ICT Consultants**
- [x] Add column at the end to add/edit months
- [x] Make family inputs clearer, e.g. "Add male member"

**Small Updates**
- [ ] #63
- [ ] Show loading screen while waiting to share (button slow to disable, should include timeout to revert on issue)
- [ ] Advanced card options (e.g. repeat x months/days/weeks)

**Medium Updates**
- [ ] Add methods to display a single svg for dot values instead of lots of individual images (create image programmatically, ideally caching in memory as required to avoid too much recalculation)
- [ ] Add budget tagging/categorisation/grouping
- [ ] Include summary in shared budget (e.g. profit/loss, consumed, labour)

**Large Updates**
- [ ] Link all rows with specific activities
- [ ] End-to-end automated test

## Feedback Completed
- [x] Add overall summary to budget screen and saved budgets list screen
- [x] Add ability to add months to budget
- [x] Add budget tools sidebar
- [x] Add new columns
- [x] Delete column 
- [x] Summary of produced/kept/cash/family labour balance need to be added
- [x] Make it easier to add values to inputs (people don't see the nested slider) #116
- [x] Fix various change detection and data duplication bugs
- [x] Show family labour split by gender
- [x] #62
- [x] Improve overall display for mobile devices (likely using more popup content and less on page) #116
- [x] Fix increase/decrease scale update
- [x] Add/Delete month
- [x] Show budget summary on home page (e.g. profit/loss, consumed, labour)
- [x] Fix bug where sometimes icons are duplicated (likely better to bypass db for hardcoded cards)

**Comment by chrismclarke** [comment]
Tracking for specific app features and improvements has been moved to [E-PICSA Issue Triage](https://docs.google.com/spreadsheets/d/17OqUtZZO5aznegT1TSGPtdYOhmtfhBYycgIYx7z0LTs/edit?usp=sharing) Google Sheet instead. Closing here
