### ISSUE TITLE
[Checklist #1] Historical Climate component

### ISSUE THREAD

**Issue by chrismclarke** [e-picsa/picsa-apps#52]
## Next Priorities
- [x] Automate station select using nearest station #276
- [x] Connect to the climate information system
- [x] Add support for temp charts

---
## Feedback TODO
**UOR feedback**
- [ ] Add significance comment such as hotter, colder dryer, wetter and not significant
- [ ] Historical monthly temperature data to be added in the app(test not real data by Feb 2023 and real data by June 2023)

**Misck Feedback**
- [x] Integrate crop water requirements display

## Feedback Completed
- [x] Fix end of season charts showing incorrect axis
- [x] Add date-picker to line tool for start/end graphs
- [x] Provide terciles display 
- [x] Improve display for smaller devices
- [x] Additional graphs for extreme events such as rainfall events and dry spells

**Comment by chrismclarke** [comment]
Thanks Rieko, just to confirm that any comments you add do indeed come through in a visible way for me. 
There's quite a few different ways to receive notifications, so if you ever feel that you are/aren't receiving the right amount of notifications from github just let me know and I can try give some tips. 

As for the charts, do we have any examples? I'm guessing length of dry spells would be a standard line chart similar to the rainfall one, but would the extreme rainfall events be a bar chart or something else?

**Comment by riekoshibata** [comment]
Hi Chris, thank you very much for your message. Good to know that when we comment in this way you can receive timely notifications! For me as well, your comment came through my email. 
Regarding the extreme rainfall events, probably "number of extreme rainfall events" can be expressed by either line or bar... (like the link below?).
https://ebrary.net/41121/geography/trends_extreme_rainfall_events_based_gridded_data
Next Monday, there will be a discussion about app components, so I will confirm how best the data could be presented.

**Comment by chrismclarke** [comment]
Tracking for specific app features and improvements has been moved to [E-PICSA Issue Triage](https://docs.google.com/spreadsheets/d/17OqUtZZO5aznegT1TSGPtdYOhmtfhBYycgIYx7z0LTs/edit?usp=sharing) Google Sheet instead. Closing here
