### ISSUE TITLE
[Checklist #10] Data collection and Monitoring

### ISSUE THREAD

**Issue by chrismclarke** [e-picsa/picsa-apps#55]
## Development Priorities
- [x] Add dashboard pages and db bindings to store forms and submissions #231
- [x] Ability to upload xlsx forms to dashboard and have them converted into enketo forms #248
- [ ] Add results view page (TBD - how/what should users nad/or admins be able to see? Dashboard vs app pages)
- [ ] Add support for forms with field validation

## 2023-04-19 Focal Points Feedback

- [ ] Support photos
- [ ] Add translations
- [ ] Consider how to include analytics/summary of data
- [ ] See feedback on [google slide](https://docs.google.com/presentation/d/1ac-qEhq3ygxRp4w3oSXDrSbSc33IoGn8/edit#slide=id.p6)

## UoR Feedback

- [ ] Data on how farmers did / performed
- [ ] Monitoring forms for extension workers(DACOs, supervisors). Gender aspect should be added

## Description
We need a system to allow collection of monitoring and survey forms

## Updates 2022-11
App UI
- [x] Create standalone monitoring tool with form list and form view pages
- [x] Integrate monitoring tool into extension app
- [x] Integrate created odk/enketo web version into form display
- [ ] Improve form list page UI
- [ ] Hide forms depending on deployment/configuration
- [ ] Add support to print form from app

Form display UI
- [ ] Add support for multiple page displays
- [ ] JR images not shown (TBC if issue)
- [ ] Datepicker not working (should replace with HTML picker)
- [ ] Add save draft, submit, next and menu buttons (e.g. https://enketo.ona.io/preview/poiB)

ODK Forms
- [ ] Create app feedback form
- [ ] Add additional PICSA forms for testing
- [ ] Add more testing forms for core functionality (e.g. multiple pages)
- [ ] Add widget testing form [xlsx form link](https://docs.google.com/spreadsheets/d/1af_Sl8A_L8_EULbhRLHVl8OclCfco09Hq2tqb9CslwQ/edit#gid=0), preview via [converter link](https://getodk.org/xlsform/)

Backend
- [x] Rewrite enketo-core for local integration as webcomponent
- [x] Create infrastructure to build and embed webcomponents in the app
- [ ] Kobo server integration (TBC)
- [ ] PICSA server integration (TBC)

Documentation
- [ ] Known limitations (e.g. removed digest functions, geopicker, themes)
- [ ] Adding forms

## TODO
**PoC**
- [x] #73
- [ ]  feedback form for users to submit overall feedback(technical, bugs and general) for the picsa app

**Discussions**
- [ ] How important is it to align with ODK?

**Design**
- [ ] Forms page
- [ ] Data view page

**Frontend Dev**
- [ ] TBD (depending on tools used)

**Backend Dev**
- [ ] Survey for data collection (if not using ODK)

## Additional Notes
App already has some legacy survey-js code and display pages. We also have tried previously embedding odk forms as an iframe, however this is not ideal as hard to track what forms have pending submissions or to force submission without re-opening the surveys. Suggested alternatives:

1) Wait for enketo deployment of `https://github.com/enketo/enketo-express/pull/454` to allow better iframe event monitoring
2) Try to recreate direct embed instead of iframe using code fro[m ](https://github.dev/enketo/enketo-express/blob/master/public/js/src)[https://github.dev/enketo/enketo-express/blob/master/public/js/s](https://github.dev/enketo/enketo-express/blob/master/public/js/src)rc (built via esbuild). Can also see how platforms like kobo embed their widgets. Benefit of this would be direct access to indexeddb used for forms
3) Abandon ODK for alternative systems (e.g. surveyjs)

Will also need to carefully check any license requirements for platforms used (e.g. attribution)

**Comment by KingMike100** [comment]
- [ ] Under these forms, there’s a need to add a feedback form for users to submit overall feedback(technical, bugs and general) for the picsa app

**Comment by chrismclarke** [comment]
Close as reported during reports and no longer needs to be tracked explicitly. Additionally the feature has mostly been dropped due to high compliance requirements for safe storage and processing of potentially sensitive information (prefer to use alternate tools instead)
