### ISSUE TITLE
[Checklist #6] Interactive training materials and videos

### ISSUE THREAD

**Issue by chrismclarke** [e-picsa/picsa-apps#57]
## Next Priorities
- [ ] video / interactive way to show farmers how to use the app
- [ ] Farmer activity multiple tools (risk needs climate and crop sheets)
- [x] #219
---

### 2024-02 Direct-to-Farmer
- [ ] UI Proposed Updates [UoR Slides](https://docs.google.com/presentation/d/1bFrqFh8R9r8JfKSzFMHgCw3xfQ3-oiS_/edit?usp=drive_web&ouid=104305379976701296755&rtpof=true)
- [ ] Audio playback integration
- [ ] Update languages select to support Chichewa (Eastern) and Nyanja (Lusaka) in Zambia
- [ ] Video playback menu (not possible android native but could consider using web player with custom full screen mode)
- [ ] Support for photo upload for any activities completed on paper #240

### 2023-12
- [ ] Farmer activity multiple tools (risk needs climate and crop sheets)
- [ ] Farmer activities content page (include summary and task, depends on UoR team)
- [ ] Farmer activities home page alt. version more ordered (either with numbers or vertical layout) for more prescriptive structure
- [ ] Tool summary/key point pages and content
- [ ] Language improvements (e.g. option tool confusion)

### Misc
- [x] #58
- [ ] show file download size #254
- [ ] Allow specifying only parent collection and automatically populating child resources
- [ ] #72
- [ ] Support for _group_ resource type to provide specific link/filter to social groups such as twitter, facebook and whatsapp
- [ ] Download all feature #254

## Feedback Completed
- [x] Direct-to-farmer home page with interactive manual sections #138
- [x] #160
- [x] Videos to remind farmers of PICSA steps
- [x] Compressing videos
- [ ] Adding subtitles
- [x] Add powerpoint with narration
- [x] #56
- [x] Gender resources section (links from email 2022-10-17) #76

## Possible enhancements
- Use [Remotion](https://www.remotion.dev/) to create videos programatically, render as still images or extract thumbnail stills
- Use [H5P](https://h5p.org/) via [Lumi Education](https://app.lumi.education/) to add layer of interactive videos
- Use [XAPI](https://xapi.com/ecosystem/) via [TinCanJS](https://www.npmjs.com/package/tincanjs) to record e-learning compliant data
- Consider [video codec](https://www.remotion.dev/docs/encoding) (probably recommend h.265/vb9)

**Comment by chrismclarke** [comment]
Tracking for specific app features and improvements has been moved to [E-PICSA Issue Triage](https://docs.google.com/spreadsheets/d/17OqUtZZO5aznegT1TSGPtdYOhmtfhBYycgIYx7z0LTs/edit?usp=sharing) Google Sheet instead. Closing here
