### ISSUE TITLE
[Checklist] Automation

### ISSUE THREAD

**Issue by chrismclarke** [e-picsa/picsa-apps#68]
- [x] Add automated play store releases
- [x] Add automated web app releases
- [ ] #69
- [ ] Image compression (already have for map tiles, should consider svgomg equiv or squoosh, possibly just documentation short term for developers but future automation step)
- [x] Semantic/automated release notes

**Comment by chrismclarke** [comment]
Closing as relevant items have either been moved to standalone issue or handled via process
