### ISSUE TITLE
[Checklist #2] Probability and risk component: Crop information/options

### ISSUE THREAD

**Issue by chrismclarke** [e-picsa/picsa-apps#89]
## Next Priorities
- [ ] Integrate live data format 🚧 - blocked pending api updates by partners
---
## Feedback TODO
- [ ] ...

## Feedback Complete
- [x] Add support for content translations (related [docs](https://docs.picsa.app/translations))
- [x] Initial prototype for crop information sheet #121 
- [x] Add basic filtering by crop
- [x] Integrate into main app - @chrismclarke #123
- [x] Include custom icons to allow filtering through visual buttons (related [docs](https://docs.picsa.app/advanced/icons)), can also see how they have been included in the material.module file of the options tool `apps\picsa-tools\option-tool\src\app\components\material.module.ts` - @FaithDaka #130 
- [x] Add support for query parameters to allow loading a crop info table for a specific site by url (e.g. /crop-probability?site=chipata) @FaithDaka #134

**Comment by chrismclarke** [comment]
Tracking for specific app features and improvements has been moved to [E-PICSA Issue Triage](https://docs.google.com/spreadsheets/d/17OqUtZZO5aznegT1TSGPtdYOhmtfhBYycgIYx7z0LTs/edit?usp=sharing) Google Sheet instead. Closing here
